// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PostalTracking.DAL.Entities;
using System;

namespace PostalTracking.DAL.Migrations
{
    [DbContext(typeof(PostalTrackingContext))]
    [Migration("20180203131851_AddStatusActive")]
    partial class AddStatusActive
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PostalTracking.DAL.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<string>("Address")
                        .HasMaxLength(150);

                    b.Property<string>("City")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .HasMaxLength(50);

                    b.Property<string>("Ponumber")
                        .HasColumnName("PONumber")
                        .HasMaxLength(50);

                    b.Property<string>("State")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("PostalTracking.DAL.Entities.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<int?>("ReceiverId")
                        .HasColumnName("ReceiverID");

                    b.Property<int?>("SenderId")
                        .HasColumnName("SenderID");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Package");
                });

            modelBuilder.Entity("PostalTracking.DAL.Entities.PackageTracking", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("ID");

                    b.Property<int?>("PackageId")
                        .HasColumnName("PackageID");

                    b.Property<int?>("StatusId")
                        .HasColumnName("StatusID");

                    b.Property<DateTime?>("StatusTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("StatusId");

                    b.ToTable("PackageTracking");
                });

            modelBuilder.Entity("PostalTracking.DAL.Entities.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<bool>("Active");

                    b.Property<string>("StatusDescription")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("PostalTracking.DAL.Entities.Package", b =>
                {
                    b.HasOne("PostalTracking.DAL.Entities.Customer", "Receiver")
                        .WithMany("PackageReceiver")
                        .HasForeignKey("ReceiverId")
                        .HasConstraintName("FK_Package_Customer1");

                    b.HasOne("PostalTracking.DAL.Entities.Customer", "Sender")
                        .WithMany("PackageSender")
                        .HasForeignKey("SenderId")
                        .HasConstraintName("FK_Package_Customer");
                });

            modelBuilder.Entity("PostalTracking.DAL.Entities.PackageTracking", b =>
                {
                    b.HasOne("PostalTracking.DAL.Entities.Package", "Package")
                        .WithMany("PackageTracking")
                        .HasForeignKey("PackageId")
                        .HasConstraintName("FK_PackageTracking_Package");

                    b.HasOne("PostalTracking.DAL.Entities.Status", "Status")
                        .WithMany("PackageTracking")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("FK_PackageTracking_Status");
                });
#pragma warning restore 612, 618
        }
    }
}
